### ISSUE TITLE
Can't send message to closed websocket

### ISSUE THREAD

**Issue by Cbsunshine** [P233/emmet2-mode#3]
I have followed the install instructions for deno. And was successful in following the testing instructions for it. I copied and pasted the code into my init.el file. I receive a error message about a closed websocket when I try to use emmet-expand.

Cannot send message to a closed websocket: #s(websocket-frame text "[\"data\",[\"html\",\"!\",1,2,\"css\",\"clsx\"]]" nil t)

This is what was output to the minibuffer when I tried to expand ! Into html5 boilerplate.

Thanks so much!

**Comment by P233** [comment]
I am sorry that I just noticed this issue. This is caused by a compatibility issue with Deno 2. I have updated it and now Deno 2.0 is required. Sorry for the late reply and inconvenience.

**Comment by reteov** [comment]
I've found the following workaround that mostly seems to work:  Use `list-processes` in Emacs to view a list of running processes.  The deno process is one of them.  Copy that command line, and then run it from a terminal prompt.  Once it's running in the prompt (and you've confirmed the access request), everything should work.
